        <table width="100%" border="0" cellspacing="5" cellpadding="5">
		  <tr>
		    <td width="45%">
			  &nbsp;
			</td>
		    <td align="center">
                <a href="javascript:clearResults();" class="bo_Button100" title="Clear the Results">Clear</a>
		    </td>
		    <td align="center">
                <a href="javascript:clickRun();" class="bo_Button100" title="Lists the status of the tables">Run Status</a>
		    </td>
		    <td align="center">
                <a href="javascript:clickUpdate();" class="bo_Button100" title="Update all the subscriber tables to match publisher">Update</a>
		    </td>
		    <td align="center">
                <a href="javascript:close();" class="bo_Button100" title="Closes this window">Close</a>
		    </td>
		    <td width="45%">
			  &nbsp;
			</td>
		  </tr>
        </table>
