<style>
  .page-heading {display: block; text-align: right;}
  .watermark {display: inline-block; font-size: 18px !important; font-weight: bold; color: #C9BB9E; margin: .125em;}
  .page-title {text-align: center; margin-left: auto; margin-right: auto; font-size: 1.5em; font-weight: bold; color: #000000; margin-top: .125em; margin-bottom: 0em; line-height: 50%;}
  .menu {margin-top: 0em; width: 100%;}
  .ugly {border: none !important; margin: 0em; padding: 0em; width: 100%;}
</style>

<div class="page-heading">
  <div class="watermark">
    Harvest American - Back Office
  </div>
  <div class="page-title">
    <h1>
      <%=PageHeading%>
    </h1>
  </div>
  <div class="menu"> 
    <table align="center" cellspacing="0" cellpadding="0" class="ugly">
      <!--#include virtual="ha_Backoffice/includes/menu/PageMenu.inc"-->
    </table>
  </div>
</div>
