  <table width="1200px" border="0" cellspacing="0" cellpadding="0" align="center">
    <tr> 
	  <td>
	    <table border="0" cellspacing="0" cellpadding="0">
		  <tr>
			<td align="left" style="font-size: 8pt;
								background-color: #D8C9AA;
								font-weight: bold;"> 
			  Copyright &copy;&nbsp;2008-<%=DatePart("yyyy", date) %>
			  Harvest American, Inc. All Rights Reserved.
			</td>  
		  </tr>
		</table>
      </td>
	</tr>
  </table>
