  <table width="100%" border="0" cellspacing="0" cellpadding="0">
    <tr> 
      <td align="right" style="padding-right: 2px; 
							   font-size: 18px;
							   font-weight: bold;
							   color: #C9BB9E;
                               margin: .125em;"> 
		<span style="font-size: 8pt;">
			<a href="/includes/logout.asp" style="color: #C9BB9E;">LOGOUT</a>
			&nbsp;&nbsp;
		</span>
        Harvest American - Back Office
      </td>
	</tr>
    <tr> 
      <td align="center" style="padding-right: 2px; 
								font-size: 24px;
								font-weight: bold;
								color: #000000;"> 
        <%=PageHeading%>
      </td>
	</tr>

	<!--#include virtual="ha_Backoffice/includes/menu/PageMenu.inc"-->
	
  </table>
