<%
  strPathCasper   = "https://casper10.harvestamerican.info/"
  strPathCTBO     = strPathCasper & "ha_Backoffice/"
  strPathCTInc    = strPathCasper & "includes/"
  strPathCTBOInc  = strPathCTBO & "includes/"
  strPathCTEmp    = strPathCTBO & "Employees/"
  strPathCTCo     = strPathCTBO & "Company/"  
%>
<script type="text/javascript">
  var strPathCasper = '<%=strPathCasper %>';
  var strPathCTEmp  = '<%=strPathCTEmp %>';
  var strPathCTCo   = '<%=strPathCTCo %>';
</script>