
  <div id="mouseoverDiv" class="mouseoverDiv">
    <table width='100%' border="2" cellspacing="2" cellpadding="2" bordercolor='black'>
      <tr valign='top'>
        <td>

          <table width='100%' border='0' cellspacing='0' cellpadding='0')

            <tr valign='top'>
              <td align='center'>
                <font size='2'>
                  <b><span id='mouseoverTitle'>Topic Goes Here</span></b>
                </font>
              </td>
            </tr>

            <tr>
              <td align='center'>
                <hr>
              </td>
            </tr>

            <tr valign='top'>
              <td width='100%'>
                <font size='1'>
                <span id='mouseoverBody'>
                  This is where the mouseover text will go.
                </span>
                </font>
             </td>
            </tr>

          </table>

        </td>
      </tr>
    </table>
  </div>
