<table class="MainTable">
  <tr><td>&nbsp;</td></tr>
  <tr>
	<td align="center">
	  <table width="95%" cellpadding="2" cellspacing="2">
		<tr>
		  <td>
			Constant Contact is a vendor who sends bulk E-mails for us.  Our mailing lists with them
			needs to be frequently updated.  Here you can export lists from our data into csv files 
			for uploading into Constant Contact.
		  </td>
		</tr>

		<tr><td>&nbsp;</td></tr>
		
		<tr>
		  <td align="right">
			<a href="javascript:clickPopup(1405);" class="TopRightLink">How to Work with Constant Contact Mailing Lists</a>
		  </td>
		</tr>
  
		<tr><td>&nbsp;</td></tr>
		
		<tr>
		  <td>
			<table width="100%" cellpadding="0" cellspacing="0">
			  <tr>
				<td width="70%">
				  <span class="newStyleHeading">Harvest</span><br><br>
					  <span style="font-weight:bold;color:#62b5f0;">All Raffle Ticket Customers:</span> Used for Marketing/Newsletter.<br/>
					  Exports from Customer Account:  first name, email address.
				  <br>
				</td>
				<td width="2.5%" id="tdCounts"><b>Counts</b><br><br><span id="ha_Software">    
				 <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" />
				</span><br><br>
				<span  id="ha_Paper">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" /></span><br><br>
				<span id="ha_Both">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" /></span><br><br></td>
				<td align="right" valign="bottom" style="text-align:center" width="15%">
				<b>Download</b></br/></br/>
				  <a href="javascript:clickDownload('SoftwareRT');" class="greenButton" style="width:300px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Software Only &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a><br/><br/>
				   <a href="javascript:clickDownload('Paper');" class="greenButton" style="width:300px;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  Paper Only &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></br/><br/>
				    <a href="javascript:clickDownload('BothSoftAndPaper');" class="greenButton"  style="width:300px;">Both Software and Paper</a></br/></br/>
				</td>
			  </tr>
			  
			  <tr><td>&nbsp;</td></tr>
			  </tr><td colspan="3"><hr></td></tr>
			  <tr><td>&nbsp;</td></tr>
			  
							
			  <tr>
				<td>
				  <span class="newStyleHeading">Zip2Tax</span>
					
					<br><br>										
					<span style="font-weight:bold;color:#62b5f0;">All Zip2Tax Customers:</span>  Used to notify All Zip2Tax Customers.<br/>
					Exports from Orders: all Zip2Tax orders<br/>
					Exports from Customer Account: first name, email address
				</td>
				<td width="2.5%" id="tdCounts" style="text-align: -webkit-right; vertical-align: bottom;">
				<span id="z2t_AllCustomers">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" />
				</span></td>
				<td align="right" valign="bottom">
				  <a href="javascript:clickDownload('AllCustomers');" class="greenButton">Download</a>
				</td>
			  </tr>
						
			  <tr><td>&nbsp;</td></tr>
			  
			  <tr>
				<td>
					
					<span style="font-weight:bold;color:#62b5f0;">Table Upload Customers:</span>  Used to notify Table customers when new tables are ready.<br/>
					Exports from Product list: only customers with Table subscriptions <br/>
					Exports from Customer Account: Organization Name<br/>
					Exports from Product Edit: all three email addresses, the login, the password <br/>
				</td>
				<td width="2.5%" id="tdCounts" style="text-align: -webkit-right; vertical-align: bottom;">
				<span id="z2t_TableUploadCustomer">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" />
				</span></td>
				<td align="right" valign="bottom">
				  <a href="javascript:clickDownload('TableUpdateCustomers');" class="greenButton">Download</a>
				</td>
			  </tr>
			  <tr><td>&nbsp;</td></tr>
			  
			  <tr>
				<td>
					<span style="font-weight:bold;color:#62b5f0;">INCOMPLETE 15-Day Free Trial Sign-ups: </span>
					Used to send emails to prospects who did not complete the 2nd part of the enrollment.<br/>
					Export: first name, email address. <br/>
					Export: login, password<br/>
				</td>
				<td width="2.5%" id="tdCounts" style="text-align: -webkit-right; vertical-align: bottom;">
				<span id="z2t_FreeTrialIncomplete">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" /></span></td>
				<td align="right" valign="bottom">
				  <br/><a href="javascript:clickDownload('FreeTrialCustomersIncomplete');" class="greenButton">Download</a>
				</td>
			  </tr>
			  
			  <tr><td>&nbsp;</td></tr>

			  <tr>
				<td>
					<span style="font-weight:bold;color:#62b5f0;">COMPLETE 15-Day Free Trial Customers:</span>
					Used to send emails to customers who enrolled but haven't subscribed to a product yet.<br/>
					Exports from Product List: customers enrolled in 15-day Free Trial product <br/>
					Exports from Customer Account:  first name, email address<br/>
					Exports from Product Edit: create date, expiration date<br/>
				</td>
				<td width="2.5%" id="tdCounts" style="text-align: -webkit-right; vertical-align: bottom;">
				<span id="z2t_FreeTrialComplete">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" /></span></td>
				<td align="right" valign="bottom">
				  <a href="javascript:clickDownload('FreeTrialCustomersComplete');" class="greenButton">Download</a><br/>

				</td>
			  </tr>

			  <tr><td>&nbsp;</td></tr>
			  
			  <tr>
				<td>
					<span style="font-weight:bold;color:#62b5f0;">Customer Renewals:</span>used to send Customers a renewal email reminder.<br/>
					Exports from Orders (Mock) List: order id <br/>
					Exports from Customer Account:  first name, last name,  email address<br/>
					Exports from Orders: account ID, item description(s)   <br/>
					Exports from Product Edit: expiration date<br/>
				</td>
				<td width="2.5%" id="tdCounts" style="text-align: -webkit-right; vertical-align: bottom;">
				<span id="z2t_CustomerRenewals">     <img id="loader" src="/ha_Backoffice/images/AjaxLoading.gif" /></span></td>
				<td align="right" valign="bottom">
				  <a href="javascript:clickDownload('CustomerRenewals');" class="greenButton">Download</a>
				</td>
			  </tr>
			  <tr><td>&nbsp;</td></tr>
			  </tr><td colspan="3"><hr></td></tr>
			</table>
			
		  </td>
		</tr>
	  </table>		
		
	</td>	
  </tr>
</table>
