<h2>Backoffices</h2>
	<ul>
  		<li><a href="http://crm.harvestamerican.info">CRM</a></li>
        <li><a href="http://www.harvestamerican.info/ha_Backoffice/ha_Home.asp">Backoffice - Harvest</a></li>
        <li><a href="http://info.zip2tax.com/z2t_Backoffice/home/z2t_home.asp">Backoffice - Zip2tax</a></li>
	</ul>

<h2>Test Page</h2>	
	<ul>
  		<li>
			<a href="https://info.zip2tax.com/z2t_Backoffice/subscribers/popups/z2t_LinkTest.asp?zip=13316&usr=davesqllinktest&pwd=goodacct2test7&v=1.1">
				Zip2Tax Service Test</a>
		</li>
	</ul>

<h2>Domains</h2>
	<ul>
		<li><a href="http://www.harvestamerican.com">HarvestAmerican.com</a>
		<li><a href="http://www.doityourselftickets.com">DoItYourselfTickets.com</a></li>
		<li><a href="http://www.eyeoncamden.com">EyeOnCamden.com</a></li>
		<li><a href="http://www.QSLPaper.com">QSLPaper.com</a></li>
		<li><a href="http://www.raffleticketsoftware.com">RaffleTicketSoftware.com</a></li>
		<li><a href="http://www.ShipHeroes.com">ShipHeroes.com</a></li>
		<li><a href="http://www.zip2tax.com">Zip2Tax.com</a> 
	</ul>

