			<h2>Camden, New York</h2>

                <div class="photo webcam">
                 <a href="http://www.harvestamerican.us/images/EyeOnCamden2b.jpg" rel="lightbox[webcams]" title="Eye On Camden Webcam" ><span></span><img id="webcam" name="webcam" border="0" width="201" height="141" alt="Image Loading..." src="http://www.harvestamerican.us/images/EyeOnCamden2b.jpg"/></a>
                        </div>