			<h2>Camden, NY</h2>

                <div class="photo webcam">
                 <a href="http://www.harvestamerican.us/images/EyeOnCamden2b.jpg" rel="lightbox[webcams]" title="Eye On Camden Webcam" ><span></span><img id="webcam" name="webcam" border="0" width="201" height="141" alt="Image Loading..." src="http://www.harvestamerican.us/images/EyeOnCamden2b.jpg"/></a>
                        </div>
			<h2>Marblehead, MA</h2>
                <div class="photo webcam">
                 <a href="http://icons.wunderground.com/webcamramdisk/w/a/Wavemagic/1/current.jpg" rel="lightbox[webcams]" title="Wavemagic's Webcam" ><span></span><img id="webcam2" name="webcam2" border="0" width="201" height="141" alt="Image Loading..." src="http://icons.wunderground.com/webcamramdisk/w/a/Wavemagic/1/current.jpg"/></a>
                        </div>
